/**
 * Notification types generated by the platform.
 * @readonly
 * @enum {string}
 */
export const NotificationType = Object.freeze({
    INCIDENT: 'incident',
    STATUS_CHANGE: 'status_change'
});

/**
 * Notification (alert) entity addressed to one participant of a shipment.
 *
 * @class Notification
 */
export class Notification {
    /**
     * @param {Object} params - Entity attributes.
     * @param {?number} [params.id=null] - Identifier.
     * @param {number} params.recipientId - Recipient user identifier.
     * @param {number} params.shipmentId - Related shipment.
     * @param {string} [params.shipmentCode=''] - Shipment code to display.
     * @param {string} params.type - Notification type.
     * @param {string} params.eventKey - Source event key, used to avoid duplicates.
     * @param {Object} [params.payload={}] - Event data used to build the translated message.
     * @param {?string} [params.createdAt=null] - Creation timestamp (ISO).
     * @param {boolean} [params.isRead=false] - Whether it was read.
     * @param {?string} [params.readAt=null] - First read timestamp (ISO).
     */
    constructor({id = null, recipientId, shipmentId, shipmentCode = '', type, eventKey, payload = {},
                    createdAt = null, isRead = false, readAt = null}) {
        this.id = id;
        this.recipientId = recipientId;
        this.shipmentId = shipmentId;
        this.shipmentCode = shipmentCode;
        this.type = type;
        this.eventKey = eventKey;
        this.payload = payload || {};
        this.createdAt = createdAt;
        this.isRead = isRead;
        this.readAt = readAt;
    }
}
